"""Shared class-hierarchy definitions and Retain Adjacent/Remote Accuracy
helpers, imported by gear.py, baselines/baseline_main.py, and
baselines/coun.py alike - one implementation instead of three duplicated
copies.

Retain Adjacent/Remote Accuracy (Cheng et al., "Machine Unlearning under
Retain-Forget Entanglement," https://arxiv.org/abs/2603.26569) partitions the
retain set relative to a forgotten class using a fixed, a-priori class
taxonomy: "adjacent" retain samples belong to a class sharing the forgotten
class's coarse superclass; "remote" retain samples belong to every other
superclass. Both are reported as ordinary micro-averaged top-1 accuracy -
this is not a distance/embedding-based metric, confirmed against the paper's
own evaluation code:
https://github.com/Jingpu-Cheng/unlearning-entanglement/blob/main/src/evaluation.py
"""

import torch
from torch.utils.data import DataLoader, SubsetRandomSampler

# CIFAR-100's official 20-superclass grouping (fine label index -> coarse
# label index), in torchvision.datasets.CIFAR100's fine-label ordering
# (alphabetical by class name - the order the dataset's own meta file uses).
CIFAR100_SUPERCLASS_MAPPING = [
    4, 1, 14, 8, 0, 6, 7, 7, 18, 3,
    3, 14, 9, 18, 7, 11, 3, 9, 7, 11,
    6, 11, 5, 10, 7, 6, 13, 15, 3, 15,
    0, 11, 1, 10, 12, 14, 16, 9, 11, 5,
    5, 19, 8, 8, 15, 13, 14, 17, 18, 10,
    16, 4, 17, 4, 2, 0, 17, 4, 18, 17,
    10, 3, 2, 12, 12, 16, 12, 1, 9, 19,
    2, 10, 0, 1, 16, 12, 9, 13, 15, 13,
    16, 19, 2, 4, 6, 19, 5, 5, 8, 19,
    18, 1, 2, 15, 6, 0, 17, 8, 14, 13,
]


# TinyImageNet has no official superclass table (unlike CIFAR-100), so this
# is an approximation: each of its 200 WordNet-synset classes is grouped with
# the most specific WordNet hypernym ancestor shared by at least 8 other
# classes (a tighter, more semantically meaningful grouping than a fixed
# tree-depth cutoff, which produces a very lopsided partition since a couple
# of WordNet branches dominate the upper levels of the tree). Generated by
# scripts/build_tinyimagenet_hierarchy.py against the dataset's own
# wnids.txt (sorted alphabetically - the order torchvision.datasets.
# ImageFolder assigns fine-label indices in, since TinyImageNet's per-class
# subdirectories are named exactly by wnid). 27 groups over 200 classes,
# e.g. group 2 ("carnivore") covers the dog/cat/lion/bear breeds, group 22
# ("structure") covers building/architecture classes, group 20 ("produce")
# covers fruits/vegetables. This is a documented approximation of the
# reference paper's own (unpublished) TinyImageNet grouping, not a faithful
# reproduction of it.
TINYIMAGENET_SUPERCLASS_MAPPING = [
    23, 23, 23, 23, 23, 23, 0, 0, 0, 0,
    0, 23, 16, 15, 15, 15, 15, 15, 0, 0,
    23, 23, 23, 19, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 15, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 19, 19, 2, 6,
    3, 22, 3, 5, 22, 22, 22, 24, 8, 24,
    21, 22, 24, 24, 10, 13, 1, 10, 22, 11,
    24, 14, 22, 6, 13, 10, 6, 8, 14, 5,
    3, 22, 6, 22, 21, 6, 22, 14, 14, 11,
    8, 11, 22, 25, 11, 10, 1, 21, 14, 13,
    8, 25, 10, 1, 11, 14, 21, 13, 6, 3,
    10, 21, 6, 6, 22, 6, 6, 13, 8, 22,
    24, 11, 11, 21, 10, 24, 6, 13, 8, 6,
    4, 6, 14, 8, 1, 14, 1, 4, 6, 3,
    3, 6, 6, 21, 22, 13, 13, 22, 10, 13,
    24, 1, 1, 6, 21, 22, 14, 22, 1, 3,
    22, 8, 24, 24, 11, 1, 1, 17, 17, 17,
    17, 9, 20, 20, 20, 20, 20, 20, 20, 20,
    9, 17, 17, 7, 18, 18, 18, 18, 18, 26,
]


def _get_superclass_mapping(data_name):
    """Returns the fine-label -> coarse-label list for a dataset, or None if
    no hierarchy is known for it - signals "not applicable" to callers,
    which should report 'N/A' rather than erroring."""
    if data_name == 'cifar100':
        return CIFAR100_SUPERCLASS_MAPPING
    if data_name == 'tinyimagenet':
        return TINYIMAGENET_SUPERCLASS_MAPPING
    return None


def get_adjacent_remote_split(data_name, forget_class, dataset):
    """Given a fine-label forget_class, returns (adjacent_indices,
    remote_indices): indices into dataset of retain-set samples (forget_class
    samples themselves are excluded from both) whose class shares the
    forgotten class's superclass (adjacent) vs. doesn't (remote). Returns
    (None, None) for datasets with no known class hierarchy."""
    mapping = _get_superclass_mapping(data_name)
    if mapping is None:
        return None, None

    forget_superclass = mapping[forget_class]
    adjacent_classes = {
        fine for fine, coarse in enumerate(mapping)
        if coarse == forget_superclass and fine != forget_class
    }

    adjacent_indices = []
    remote_indices = []
    for i, (_, label) in enumerate(dataset):
        if label == forget_class:
            continue
        if label in adjacent_classes:
            adjacent_indices.append(i)
        else:
            remote_indices.append(i)

    return adjacent_indices, remote_indices


def compute_split_accuracy(model, dataset, indices_adjacent, indices_remote, device, batch_size=64):
    """Ordinary micro-averaged top-1 accuracy (correct/total pooled across
    batches) over the adjacent and remote index sets, matching the reference
    paper's evaluate_on_three_datasets aggregation. Each of the two returned
    values is 'N/A' when its index list is None (no known hierarchy) or
    empty (no matching samples in this particular split)."""

    def _accuracy_over(indices):
        if not indices:
            return 'N/A'
        loader = DataLoader(dataset, batch_size=batch_size,
                            sampler=SubsetRandomSampler(indices))
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for data, target in loader:
                data, target = data.to(device), target.to(device)
                if target.dim() > 1:
                    target = target.squeeze()
                pred = model(data).argmax(dim=1)
                correct += (pred == target).sum().item()
                total += target.size(0)
        return correct / total if total > 0 else 'N/A'

    acc_adjacent = _accuracy_over(indices_adjacent) if indices_adjacent is not None else 'N/A'
    acc_remote = _accuracy_over(indices_remote) if indices_remote is not None else 'N/A'
    return acc_adjacent, acc_remote
